// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOH8BaUZSkOR_PXCauYQBcBnZe4iIjFAU',
    appId: '1:2395763225:web:764ecc5bf7aced3e1db088',
    messagingSenderId: '2395763225',
    projectId: 'fyp-book-nook',
    authDomain: 'fyp-book-nook.firebaseapp.com',
    storageBucket: 'fyp-book-nook.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDTZDR_U42uNJqOgdJBFpCQSjBIlUVEUE',
    appId: '1:2395763225:android:ff8b3f0e1b028e021db088',
    messagingSenderId: '2395763225',
    projectId: 'fyp-book-nook',
    storageBucket: 'fyp-book-nook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgsS9Ss9YqlZ4wUm8_f1D9ulxeBwkYMDQ',
    appId: '1:2395763225:ios:cd5badbf6200a36c1db088',
    messagingSenderId: '2395763225',
    projectId: 'fyp-book-nook',
    storageBucket: 'fyp-book-nook.firebasestorage.app',
    iosBundleId: 'com.example.bookNook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgsS9Ss9YqlZ4wUm8_f1D9ulxeBwkYMDQ',
    appId: '1:2395763225:ios:cd5badbf6200a36c1db088',
    messagingSenderId: '2395763225',
    projectId: 'fyp-book-nook',
    storageBucket: 'fyp-book-nook.firebasestorage.app',
    iosBundleId: 'com.example.bookNook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOH8BaUZSkOR_PXCauYQBcBnZe4iIjFAU',
    appId: '1:2395763225:web:85ccd55d764356d21db088',
    messagingSenderId: '2395763225',
    projectId: 'fyp-book-nook',
    authDomain: 'fyp-book-nook.firebaseapp.com',
    storageBucket: 'fyp-book-nook.firebasestorage.app',
  );
}
